;;;; vivace/schema.lisp -- rag-chunk vertex type and chunk<->vertex mapping.

(in-package #:cl-llm.rag.vivace)

(defun chunk-type-symbol (type)
  "The graph-db-interned symbol naming the chunk vertex TYPE."
  (intern (string type) :graph-db))

(defun chunk-constructor (type)
  "The MAKE-<type> constructor generated by def-vertex, resolved in graph-db."
  (fdefinition (intern (format nil "MAKE-~A" (string type)) :graph-db)))

(defun %slot (vertex name)
  (slot-value vertex (intern name :graph-db)))

(defun ensure-chunk-schema (graph type)
  "Idempotently declare the chunk vertex TYPE into GRAPH's live schema. Runs the
generated constructor/lookup/predicate into the graph-db package, registers the
type-meta under GRAPH's name, and instantiates it. Safe to call repeatedly and on
a reopened graph."
  (let ((tsym (chunk-type-symbol type)))
    ;; (a) Ensure the constructor exists in this image, AND the meta is registered
    ;;     under this graph's name (def-vertex does both). Skip only when this
    ;;     graph already has the type AND the constructor is already generated.
    (unless (and (gdb:lookup-node-type-by-name tsym :vertex :graph graph)
                 (fboundp (intern (format nil "MAKE-~A" (string type)) :graph-db)))
      ;; gdb:*graph* must be bound here: def-vertex's own auto-instantiate step
      ;; (triggered when a graph of this name is already registered) and
      ;; graph-db::update-schema's internal instantiate-node-type both call
      ;; lookup-node-type-by-name with an implicit :graph (gdb:*graph*)
      ;; default rather than threading GRAPH through explicitly.
      (let ((gdb:*graph* graph))
        (let ((*package* (find-package :graph-db)))
          (handler-bind ((warning #'muffle-warning))
            (eval `(gdb:def-vertex ,tsym ()
                     ((,(intern "TEXT" :graph-db) :type string)
                      (,(intern "DOCUMENT-ID" :graph-db))
                      (,(intern "METADATA" :graph-db))
                      (,(intern "EMBEDDING" :graph-db)
                       :type (simple-array double-float (*))))
                     ,(gdb:graph-name graph)))))
        (gdb::update-schema graph)))
    tsym))

(defun chunk->vertex (graph type chunk)
  "Create one graph vertex of TYPE from a rag:chunk. Call inside a transaction
with gdb:*graph* bound to GRAPH."
  (funcall (chunk-constructor type)
           :text (rag:chunk-text chunk)
           :document-id (rag:chunk-document-id chunk)
           :metadata (rag:chunk-metadata chunk)
           :embedding (rag:chunk-embedding chunk)
           :graph graph))

(defun vertex->chunk (vertex)
  "Reconstruct a rag:chunk from a chunk VERTEX, coercing the embedding back to
(simple-array double-float (*)) (VG deserialises it as a T-vector)."
  (rag:make-chunk (%slot vertex "TEXT")
                  :document-id (%slot vertex "DOCUMENT-ID")
                  :metadata (%slot vertex "METADATA")
                  :embedding (rag:as-embedding (%slot vertex "EMBEDDING"))))
